{
  "submodules": {
    "cloud": {
      "services": {
        "cloud": {
          "code": "cloud",
          "name": "Cloud",
          "type": "IHM",
          "description": "A Cloud space in read only to share data and results, using filebrowser",
          "release": "v2",
          "available": true,
          "link": {
            "available": true,
            "protocol": "http",
            "ip": "",
            "port": "4209",
            "port_inner": "80",
            "path": "files/"
          }
        }
      }
    }
  }
}