#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # setup
    stark-module-databases-submodule-gemini-service-setup:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_RESTART}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_COMMAND}
        volumes:
            # Main configuration
            # CONFIG and SERVICES
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_INNER_FOLDER_SERVICES}:rw
            # GEMINI
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_PARAM_GEMENI_DATABASES_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_PARAM_GEMENI_DATABASES_FOLDER_INNER}:rw

    # cli
    stark-module-databases-submodule-gemini-service-cli:
        depends_on: 
            - stark-module-databases-submodule-gemini-service-setup
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
        # build:
        #     context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT}
        #     dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_RESTART}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_COMMAND}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENV_FILE}
        environment:
            - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_SLEEP}
        volumes:
            # Main configuration
            # CONFIG and SERVICES
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_SERVICES}:rw
            # REPOSITORIES
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
            # DATA
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_INNER_FOLDER_DATA}:rw
            # DATABASES
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
            # GEMINI
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_INNER}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_INNER}:rw
        # ports: 
        #     - 4309:8088
        networks: 
            - ${DOCKER_STARK_MAIN_NETWORK}

    # # web
    # stark-module-databases-submodule-gemini-service-cli-web:
    #     depends_on: 
    #         - stark-module-databases-submodule-gemini-service-setup
    #     image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
    #     # build:
    #     #     context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT}
    #     #     dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT_DOCKERFILE}
    #     container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_NAME}-web
    #     restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_RESTART}
    #     #entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENTRYPOINT}
    #     #command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_COMMAND}
    #     entrypoint: gemini
    #     command: browser --use builtin --host 0.0.0.0 --port 8088 /STARK/databases/gemini/current/db/HUSHEMATO.TSOMYELOID.minimal.ann.db
    #     env_file:
    #         - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENV_FILE}
    #     environment:
    #         - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_SLEEP}
    #     volumes:
    #         # Main configuration
    #         # CONFIG and SERVICES
    #         - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_CONFIG}:ro
    #         - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_SERVICES}:rw
    #         # REPOSITORIES
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
    #         # DATA
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_INNER_FOLDER_DATA}:rw
    #         # DATABASES
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
    #         # GEMINI
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_INNER}:rw
    #         - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_INNER}:rw
    #     ports: 
    #         - 4308:8088
    #     networks: 
    #         - ${DOCKER_STARK_MAIN_NETWORK}



    # EDITH Dashboard
    stark-module-databases-submodule-gemini-service-dashboard:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_ENV_FILE}
        environment:
            - FOLDER_DATABASES=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}
            - DOCKER_STARK_PREFIX=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_DOCKER_STARK_PREFIX}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_TARGET}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_SERVICES}:rw
            # Services
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_SERVICES}:rw
            # Databases
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}:ro
            # GEMINI
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DATABASES_FOLDER_INNER}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_HOST}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_GEMENI_DB_FOLDER_INNER}:rw
            # DEV
            - /Users/lebechea/BIOINFO/git/STARK-modules/services/databases/gemini/dashboard/dockerfile/www.dev:/app
        networks:
            - stark_stark




# NETWORK
###########

networks:
    stark_stark:
        external: true
