##########################################################################
# Config Yaml Version:     1.0
# Description:             Yaml file to run Snakefile Filt3r module
##########################################################################
# DEV version 1 : 28/11/2023
# Authoring : Thomas LAVAUX
################## Directories and variables ##################
# Name of the module = {serviceName} from listener.py/launcher.py
serviceName: "FILT3R"

# Default repository/depository path from listener.py/launcher.py
repository: "/STARK/output/repository"
depository: "/STARK/output/depository"
# Copy to depot directory (archive)
DEPOT_COPY: False
# Output directory if not repository
OUTPUT_DIR: ""

# Default path to the input datas == {run} from listener.py/launcher.py
run: ""
# Group and App default name
GROUP_NAME: "UNKNOWN"
APP_NAME: "UNKNOWN"
# Bed file
BED_FILE: ""
# Genes file
GENES_FILE: ""
# Transcripts file
TRANSCRIPTS_FILE: ""
# List genes
LIST_GENES: ""

# Ext to index (endwith)
EXT_INDEX_LIST : [".cram", ".cram.crai", ".transcripts", ".manifest.genes", ".design.bed", ".bam", ".bam.bai"]
# List of files extension to process
PROCESS_FILE: ['.bam']
# How to process input files : cram/cp/rsync/ls/filterbam
PROCESS_CMD: 'cp'
# Only analyse validation.bam/cram files
VALIDATION_ONLY: False
# Append an aligner name if no empty (from sample.bam to sample.aligner_name.bam)
ALIGNER_NAME:

# Samples list exclusion (not to be analyse) ; exclude if startwith, case insensitive
EXCLUDE_SAMPLE: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC', 'Blc']
# Sample filter
FILTER_SAMPLE: []

# Rsync options : if several files are added add {} at the start and end of the list
# include_rsync must have more than one argument
EXCLUDE_RSYNC: "'*'"
INCLUDE_RSYNC: "{'*.tsv', '*.vcf.gz'}"
# for log file copy if pipeline failed
INCLUDE_LOG_RSYNC: "{'*.log','*.err','*Failed.txt'}"

# Search parameters
RECURSIVE_SEARCH: False
SEARCH_ARGUMENT: "/*/STARK/*"

# MISC
THREADS: "4"
## DEBUG ##
DEBUG_MODE: False

################## Tools parameters ##################

################## filt3r ##################
KMER: "12"
# GRCH37 or 38 ref fasta sequence
ITDREF: "/STARK/database/ITDs/FLT3/filt3r/flt3_hg19.fa"
