##########################################################################
# Config Yaml Version:     0.2
# Description:             Yaml file to run Snakefile FLT3_ITD_EXT module
##########################################################################
# DEV version 0.2 : 05/03/2023
# Authoring : Thomas LAVAUX
################## Directories and variables ##################
# Name of the module = {serviceName} from listener.py/launcher.py
serviceName: "FLT3ITDEXT"

# Default repository/depository path from listener.py/launcher.py
repository: "/STARK/output/repository"
depository: "/STARK/output/depository"
# Copy to depot directory (archive)
DEPOT_COPY: False
# Output directory (default is repository) ; if not NULL, it won't copy in repository
OUTPUT_DIR: ""

# Default path to the input datas == {run} from listener.py/launcher.py
run: ""
# Group and App default name
GROUP_NAME: "UNKNOWN"
APP_NAME: "UNKNOWN"
# Bed file
BED_FILE: ""
# Genes file
GENES_FILE: ""
# Transcripts file
TRANSCRIPTS_FILE: ""
# List genes
LIST_GENES: ""

# Files to index into the dictionary depending on extension (endwith)
EXT_INDEX_LIST : [".cram", ".cram.crai", ".transcripts", ".manifest.genes", ".design.bed", ".bam", ".bam.bai"]
# List of files extension to process
PROCESS_FILE: ['.bam']
# How to copy input files : ls or rsync
PROCESS_CMD: 'ls'
# Append an aligner name if no empty (from sample.bam to sample.alignername.bam)
ALIGNER_NAME:
# Only analyse sample.validation.aligner.bam/cram files
VALIDATION_ONLY: False

# Samples list exclusion (not to be analyse) ; exclude if startwith, case insensitive
EXCLUDE_SAMPLE: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC', 'Blc']
# Sample filter
FILTER_SAMPLE: []

# Extension files to copy after pipeline success
# using brace extension, remove space between extensions
INCLUDE_RSYNC: "{'*.vcf.gz.tbi','*.vcf.gz','*/'}"
# Extensions files to copy after pipeline failure
INCLUDE_LOG_RSYNC: "{'*.log','*.err','*Failed.txt'}"

# Search parameters
RECURSIVE_SEARCH: False
SEARCH_ARGUMENT: "/*/STARK/*"

# Misc
THREADS: "4"
## DEBUG ##
DEBUG_MODE: False

################## Tools parameters ##################
# Folder to store dummy.vcf for ex
DUMMY_PATH: "/app/config/"
REFGENEFA_PATH: "/STARK/databases/genomes/current/hg19.fa"
# Option to filter vcf with bcftools
# ex "-i 'FORMAT/DP>=30 && FORMAT/RAF>=0.01'"
BCFTOOLS_FILTER: "-i 'INFO/RAF>=0.01'"
################## flt3_itd_ext ##################
REF_ITD_PATH: "/STARK/databases/ITDs/FLT3/flt3itdext/FLT3_dna_e14e15"
# Assembly (hg19/hg38)
ASSEMBLY: "hg19"
# Type of sequencing technology (HC = capture)
NGS_TYPE: "HC"
# Min of reads to considere an ITD
MINREADS: "5"