{
  "submodules": {
    "jarvis": {
      "services": {
        "vision": {
          "code": "vision",
          "name": "JARVIS/VISION",
          "description": "VCF Browser JARVIS [Just A Rather Marvellous Variant Interface System] - VISION [Vcf vIewer and Simplified prioritizatION] - JARVIS is an efficient software tool functionally annotating genetic variants in order to detected causative cancer mutations",
          "release": "1.0.2b",
          "type": "IHM",
          "available": true,
          "link": {
            "available": true,
            "protocol": "http",
            "ip": "",
            "port": "4204",
            "port_inner": "80",
            "path": "vision.php"
          }
        },
        "friday": {
          "code": "friday",
          "name": "JARVIS/FRIDAY",
          "description": "VCF Browser JARVIS [Just A Rather Marvellous Variant Interface System] - FRIDAY [Full Row Interface to Deal with Annotation dictionnarY] - FRIDAY is an spreadsheet like interface providing genetic variants proritization and visualization in VCF format",
          "release": "1.0b",
          "type": "IHM",
          "available": false,
          "link": {
            "available": false,
            "protocol": "http",
            "ip": "",
            "port": "4204",
            "port_inner": "80",
            "path": "friday.php"
          }
        }
      }
    }
  }
}