{
  "submodules": {
    "vcfminer": {
      "services": {
        "vcfminer": {
          "code": "vcfminer",
          "name": "VCF-Miner",
          "description": "Graphical user interface for sorting, filtering and querying information encoded in VCF files",
          "release": "20150814",
          "type": "IHM",
          "available": false,
          "link": {
            "available": false,
            "protocol": "http",
            "ip": "",
            "port": "4205",
            "port_inner": "8080",
            "path": "vcf-miner/"
          }
        }
      }
    }
  }
}