#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:

    # PORTAINER
    stark-module-admin-submodule-portainer-service-portainer:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_IMAGE}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_CONTAINER_COMMAND}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_CONTAINER_RESTART}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_PARAM_PORT_TARGET}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_SOCK_MOUNT}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_PORTAINER_PARAM_FOLDER_DATA}:rw
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        labels:
            # for traefik, delete this if not needed
            traefik.enable: true
            traefik.http.routers.portainer-http.entrypoints: web
            traefik.http.routers.portainer.rule: Host(`portainer.czs.local`)
        networks:
            - stark_stark

# NETWORK
###########

networks:
    stark_stark:
        external: true
