##########################################################################
# Config Yaml Version:     0.1
# Description:             Yaml file to run Snakefile SCRAMBLE module
##########################################################################

# DEV version 0.1 : 10/11/2021
# Authoring : Thomas LAVAUX

# Add here variables that will extend default configuration yaml file.
# If a variable was already defined in the default configuration yaml file, it will be replace.

################## Directories and variables ##################

# Default repository/depository path for STARK directories structure
repository: "/STARK/output/repository"
depository: "/STARK/output/depository"

# Output directory if not repository
OUTPUT_DIR: ""

# Group and App default name
GROUP_NAME: "UNKNOW"
APP_NAME: "UNKNOW"

# Default path to the input datas == {run} from listener.py/launcher.py
run: ""

# Bed file
BED_FILE: ""
# Genes file
GENES_FILE: ""
# Transcripts file
TRANSCRIPTS_FILE: ""

# Name of the module = {serviceName} from listener.py/launcher.py
serviceName: "SCRAMBLE"

### TOOLS PATH ###
# Default path to a FASTA file with .fasta reference genome (hg19/hg38 for ex)
REFGENEFA_PATH: "/STARK/databases/genomes/current/hg19.fa"
# Default path to an FASTA file with MEI Ref sequences
REFMEI_PATH: "/tools/scramble/current/resources/MEI_consensus_seqs.fa"
# Path to Bedtools
BEDTOOLS_PATH: "/tools/bedtools/current/bin/bedtools"
# Path to Bcftools
BCFTOOLS_PATH: "/tools/bedtools/current/bin/bcftools"
# Path to Scramble R directory scripts
SCRAMBLE_PATH: "/tools/scramble/current/bin"

# Samples list exclusion (not to be analyse)
EXCLUDE_SAMPLE_LIST: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC']
# Sample filter
FILTER_SAMPLE_LIST: []

# Ext to index (endwith)
EXT_INDEX_LIST: [".cram", ".cram.crai", ".transcripts", ".genes.bed", ".design.bed", ".fastq.gz", ".vcf.gz", ".bam", ".bam.bai"]

# Only analyse validation.bam/cram files
VALIDATION_ONLY: False
# Process .bam or .cram
PROCESS_FILE: ".bam"
# Process input files : samtools/cp/ls
PROCESS_CMD: 'ls'

# Append an aligner name if missing (from sample.bam to sample.aligner_name.bam)
ALIGNER_NAME:

# Analyse only CRAM files
CRAM_ONLY: False

# Rsync option for copy
# include_rsync must have more than one arguement
INCLUDE_RSYNC: "{'*.vcf.gz','*.vcf.gz.tbi','*.bed','*/'}"
# exclude_rsync can only take on arguement
EXCLUDE_RSYNC: "'*'"
# for log file copy if pipeline failed
INCLUDE_LOG_RSYNC: "{'*.log','*.err','*Failed.txt'}"

# Copy to depot directory (archive)
DEPOT_COPY: False

##### Search parameters for inputs ####
RECURSIVE_SEARCH: False
SEARCH_ARGUMENT: "/*/STARK/*"

## DEBUG ##
DEBUG_MODE: True

# MISC
THREADS: "4"

################## Tools specific parameters ##################
################## cluster_identifier params
m: 10 # min soft clipped bases to be put in a cluster (default 10)
s: 5 # min soft clipped reads to be a cluster (default 5)
r: all # region (default all : format ex chr9:1-20000)


################## scramble params
nCluster: 5 # min cluster size to analyze(default 5)
mei-score: 50 # min MEI alignment score to call (default 50)
poly-a-frac: 0.75 # fraction of clipped length for calling polyA tail in MEIs (default 0.75)
poly-a-dist: 100 # how far from MEI to look for polyA tail (default 100)

################## AnnotSV params
hpo: # HPO terms list describing the phenotype of the individual being investigated Values: use comma, semicolon or space separated class values Default = "" (e.g.: "HP:0001156,HP:0001363,HP:0011304") = only for individual analysis
genomeBuild: GRCh37 # GRCh38 default, set to GRCh37 for hg19
overlap: 100 # default 100
annotationMode: full # split, full or both (defaut both)