{
  "code" : "genomebrowser",
  "name": "Genome Browser",
  "fullname": "Genome Browser",
  "description": "Genome Browser STARK module provides multiple genome browsers, either internal or external.",
  "release": "1.0",
  "available": true,
  "submodules": {
    "main": {
      "services": {
        "ucsc-gbg": {
          "code": "UCSC-GBG",
          "name": "UCSC Genome Browser Gateway",
          "description": "Genome Browser UCSC GBG - UCSC Genome Browser Gateway.",
          "type": "WEB",
          "release": "1.0",
          "available": true,
          "link": {
            "available": true,
            "protocol": "https",
            "ip": "genome.ucsc.edu",
            "port": "",
            "path": "cgi-bin/hgGateway"
          }
        }
      }
    }
  }
}