{
  "code" : "STRUCTURALVARIATION",
  "name": "Structural Variation",
  "fullname": "Structural Variation detection",
  "description": "STARK Structural Variation detection such as CNV and mobile element.",
  "release": "1.0",
  "available": true,
  "services": {
    "DECoN": {
      "code": "DECoN",
      "name": "DECoN",
      "type": "IHM",
      "container": "STARK-module-STRUCTURALVARIATION-service-DECoN-IHM",
      "description": "DECoN is a CNV detection application. Its IHM provides an result interface (TODO)",
      "release": "1.0",
      "available": true,
      "link": {
        "available": false,
        "protocol": "http",
        "ip": "",
        "port": "4210",
        "path": ""
      }
    },
    "DECoN-listener": {
      "code": "DECoN-listener",
      "name": "DECoN analysis listener",
      "type": "listener",
      "container": "STARK-module-STRUCTURALVARIATION-service-DECoN-listener",
      "description": "DECoN is a CNV detection application. Its listener automatically launch analyses (TODO)",
      "release": "1.0",
      "available": true
    }
  }
}