#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:

    # HELP
    # To run service (e.g. CLI) with docker-compose run (examples):
    # Changing entrypoint 
    # env $(cat ../../.env STARK.env | grep "#" -v) docker-compose -f STARK.docker-compose.yml run --entrypoint=/STARK/tools/DECoN/current/bin/DECoN.launch.sh STARK-module-STRUCTURALVARIATION-service-DECoN_CLI /STARK/data/DECoN/Repository/HUSDIAGGEN/BRCA/CPS_AF206 /STARK/data/DECoN_DOCKER/ RUN true
    # Changing only CMD (with image entrypoint as bash, usualy the case with CLI)
    # env $(cat ../../.env STARK.env | grep "#" -v) docker-compose -f STARK.docker-compose.yml run STARK-module-STRUCTURALVARIATION-service-DECoN_CLI -c "/STARK/tools/DECoN/current/bin/DECoN.launch.sh /STARK/data/DECoN/Repository/HUSDIAGGEN/BRCA/CPS_AF206 /STARK/data/DECoN_DOCKER2/ RUN true"
    # Generic command with YML and YML-service
    # YML=services/STRUCTURALVARIATION/STARK.docker-compose.yml && YML_service=STARK-module-STRUCTURALVARIATION-service-DECoN_CLI && env $(cat $(dirname $YML)/../../.env $(dirname $YML)/STARK.env | grep "#" -v) docker-compose -f $YML run $YML_service -c "/STARK/tools/DECoN/current/bin/DECoN.launch.sh /STARK/data/DECoN/Repository/HUSDIAGGEN/BRCA/CPS_AF206 /STARK/data/DECoN_DOCKER2/ RUN true"

    # DECoN CLI
    STARK-module-STRUCTURALVARIATION-service-DECoN_CLI:
        image: ${DOCKER_STARK_SERVICE_STRUCTURALVARIATION_DECoN_CLI_IMAGE}
        build:
            context: ${DOCKER_STARK_SERVICE_STRUCTURALVARIATION_DECoN_IHM_CONTEXT}
            dockerfile: Dockerfile
        container_name: ${DOCKER_STARK_SERVICE_STRUCTURALVARIATION_DECoN_CLI_CONTAINER_NAME}
        entrypoint: /bin/bash
        command: -c "echo '#[INFO] Welcome to DECoN CLI' ; while true; do sleep ${DOCKER_STARK_SERVICE_STRUCTURALVARIATION_DECoN_CLI_SLEEP}; done"
        volumes:
            # Config
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
            # Input
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_INNER_FOLDER_DATA}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT}:${DOCKER_STARK_INNER_FOLDER_INPUT}:ro
            # Output
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
            #- ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:rw
        restart: always
        #env_file:
        #    - ${DOCKER_COMPOSE_SERVICE_STARK_MODULE_ENV}
        networks:
        #     - structuralvariation_structuralvariation
            - stark_stark


# NETWORK
###########

networks:

    stark_stark:
        external: true

    