##########################################################################
# Config Yaml Version:     1.0
# Description:             Yaml file to run FILT3R SETUP Snakefile module
##########################################################################
# PROD version 1 : 05/09/2024
# Authoring : Thomas LAVAUX

##########################################################################
# Add here variables that will extend default configuration yaml file.
# If a variable was already defined in the default configuration yaml file, it will be replace.
# launch snakemake -s snakefile_decon -c(numberofthreads) --config run=absolutepathoftherundirectory var1=0.05 var2=12
# separate multiple variable with a space
################## Directories and variables ##################

GENCODE_VERSION: "41"
ASSEMBLY: "GRCh38"
SPECIES: "human"

# Command to download (wget or aria2c)
COMMAND: "aria2c --async-dns=false -c -s 16 -x 16 -k 1M -j 1"

# Specify a DATE_TIME value (for rerun)
DATE_TIME: ""
# LOG level 30=logging.WARNING or 20=logging.INFO
LOG_LEVEL: 30