#########
# STARK #
#########
# Usage: docker-compose up



version: '3.9'


# NETWORKS
##########

networks:
  internal:
    driver: bridge
    driver_opts:
        com.docker.network.bridge.enable_ip_masquerade: 'true'
    internal: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: "10.11.0.0/16"
        - subnet: "2001:db8:1:1::/64"

# VOLUMES
#########

volumes:
  root-home:
  home:
  etc-ssh:
  etc-slurm:
  slurmctld:
  mail:
  auth:
  src:
  container-shared:
  munge:


# SERVICES
##########

services:


  db:

    image: sql_server:latest

    build:
      context: ./sql_server
      args:
        SUBNET: "10.11"
        SUBNET6: "2001:db8:1:1::"
      network: host

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=slurm
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=slurm_acct_db
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"

    volumes:
      - /dev/log:/dev/log

    hostname: db

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    networks:
      internal:
        ipv4_address: "10.11.1.3"
        ipv6_address: "2001:db8:1:1::1:3"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  slurmdbd:

    build:
      context: ./scaleout
      args:
        DOCKER_FROM: almalinux
        SLURM_RELEASE: master
        SUBNET: "10.11"
        SUBNET6: "2001:db8:1:1::"
        CACHE_DESTROYER: "1667128123"
      network: host

    image: scaleout:latest

    environment:
      - SUBNET="10.11"
      - SUBNET6="10.11"

    hostname: slurmdbd

    networks:
      internal:
        ipv4_address: "10.11.1.2"
        ipv6_address: "2001:db8:1:1::1:2"

    volumes:
      - root-home:/root
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/

      - /tmp/
      - /run/
      - /run/lock/
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /sys/firmware
      - /sys/kernel

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/
      - /var/lib/journal

      - /var/run/docker.sock:/var/run/docker.sock

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "db"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  mgmtnode:

    image: scaleout:latest

    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker

    hostname: mgmtnode

    networks:
      internal:
        ipv4_address: 10.11.1.1
        ipv6_address: 2001:db8:1:1::1:1

    volumes:
      - root-home:/root
      - home:/home/
      - slurmctld:/var/spool/slurm
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - auth:/auth/
      - src:/usr/local/src/

      - /tmp/
      - /run/
      - /run/lock/
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /sys/firmware
      - /sys/kernel

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/
      - /var/lib/journal

      - /var/run/docker.sock:/var/run/docker.sock

      - munge:/etc/munge

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "slurmdbd"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  login:

    image: scaleout:latest

    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker

    hostname: login

    networks:
      internal:
        ipv4_address: 10.11.1.5
        ipv6_address: 2001:db8:1:1::1:5

    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - home:/home/
      - slurmctld:/var/spool/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/
      - /var/lib/containers
      - /dev/fuse:/dev/fuse:rw
      - container-shared:/srv/containers

      - /tmp/
      - /run/
      - /run/lock/
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /sys/firmware
      - /sys/kernel

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/
      - /var/lib/journal

      - /var/run/docker.sock:/var/run/docker.sock

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  node00:

    image: scaleout:latest

    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker

    hostname: node00

    networks:
      internal:
        ipv4_address: 10.11.5.0
        ipv6_address: 2001:db8:1:1::5:0

    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - home:/home/
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/
      - container-shared:/srv/containers

      - /tmp/
      - /run/
      - /run/lock/
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /sys/firmware
      - /sys/kernel

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/
      - /var/lib/journal

      - /var/run/docker.sock:/var/run/docker.sock

    # ulimits:
    #   nproc:
    #     soft: 4
    #     hard: 4
    #   nofile:
    #     soft: 131072
    #     hard: 131072
    #   memlock:
    #     soft: 48000
    #     hard: 48000

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 64G
    #     # reservations:
    #     #   cpus: 6
    #     #   memory: 48G

    mem_limit: 500m

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  openondemand:

    build:
      context: ./openondemand
      network: host

    image: openondemand

    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - DEFAULT_SSHHOST=login

    volumes:
      - /dev/log:/dev/log
      - etc-ssh:/etc/shared-ssh
      - home:/home/

    networks:
      internal:
        ipv4_address: 10.11.1.21
        ipv6_address: 2001:db8:1:1::1:21

    depends_on:
      - "login"

    ports:
      - 8081:80

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined


  rest:

    hostname: rest

    image: scaleout:latest

    networks:
      internal:
        ipv4_address: 10.11.1.6
        ipv6_address: 2001:db8:1:1::1:6

    volumes:
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log

      - /tmp/
      - /run/
      - /run/lock/
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /sys/firmware
      - /sys/kernel

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/
      - /var/lib/journal

      - /var/run/docker.sock:/var/run/docker.sock

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"



  proxy:

    build:
      context: ./proxy
      network: host

    image: proxy:latest

    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker

    hostname: proxy

    command: ["bash", "-c", "nginx & php-fpm8 -F"]

    networks:
      internal:
        ipv4_address: 10.11.1.7
        ipv6_address: 2001:db8:1:1::1:7

    volumes:
      - auth:/auth/
      - /dev/log:/dev/log

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    ports:
      - 8080:8080

    depends_on:
      - "rest"

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "openondemand:10.11.1.21"
      - "openondemand:2001:db8:1:1::1:21"

