#########
# STARK #
#########
# Usage: docker-compose up



version: '3.9'


# NETWORKS
##########

networks:
  
  internal:
    driver: bridge
    driver_opts:
        com.docker.network.bridge.enable_ip_masquerade: 'true'
        #com.docker.network.bridge.enable_ipv6: 'true'
    internal: false
    enable_ipv6: true
    ipam:
      config:
        #- subnet: "10.11.0.0/16"
        - subnet: "${SUBNET}.0.0/16"
        - subnet: "${SUBNET6}:/64"

  stark_stark:
    external: 
      name: stark_stark



# VOLUMES
#########

volumes:
  root-home:
  home:
  etc-ssh:
  etc-slurm:
  slurmctld:
  mail:
  
  src:
  container-shared:
  munge:
  mysql:
  # slurmdbd
  tmp_slurmdbd:
  run_slurmdbd:
  run-lock_slurmdbd:
  journal_slurmdbd:
  # mgmtnode
  tmp_mgmtnode:
  run_mgmtnode:
  run-lock_mgmtnode:
  journal_mgmtnode:
  # login
  tmp_login:
  run_login:
  run-lock_login:
  journal_login:
  # node00
  tmp_node00:
  run_node00:
  run-lock_node00:
  journal_node00:
  # rest
  tmp_rest:
  run_rest:
  run-lock_rest:
  journal_rest:
  # Config
  cluster-cfg:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${CLUSTER_CONFIG_HOST_FOLDER}
  auth:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${CLUSTER_CONFIG_HOST_FOLDER}

# SERVICES
##########

services:


  db:

    image: stark/sql_server:latest

    build:
      context: ./sql_server
      args:
        SUBNET: "${SUBNET}" #"10.11"
        SUBNET6: "${SUBNET6}:"
      network: host

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=slurm
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=slurm_acct_db
      - SUBNET=${SUBNET}
      - SUBNET6="${SUBNET6}:"

    volumes:
      - /dev/log:/dev/log
      - mysql:/var/lib/mysql

    hostname: db

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    networks:
      internal:
        ipv4_address: "${SUBNET}.1.3"
        ipv6_address: "${SUBNET6}:1:3"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  slurmdbd:

    build:
      context: ./scaleout
      args:
        DOCKER_FROM: almalinux
        SLURM_RELEASE: master
        SUBNET: "${SUBNET}"
        SUBNET6: "${SUBNET6}:"
        CACHE_DESTROYER: "1667128123"
      network: host

    image: stark/scaleout:latest

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET}"

    hostname: slurmdbd

    networks:
      internal:
        ipv4_address: "${SUBNET}.1.2"
        ipv6_address: "${SUBNET6}:1:2"

    volumes:
      - root-home:/root
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/

      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/

      - /var/run/docker.sock:/var/run/docker.sock


      - tmp_slurmdbd:/tmp
      - run_slurmdbd:/run
      - run-lock_slurmdbd:/run/lock
      - journal_slurmdbd:/var/lib/journal

      - cluster-cfg:${CLUSTER_CONFIG_INNER_FOLDER}

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "db"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  mgmtnode:

    image: stark/scaleout:latest

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET6}:"
      - container=docker

    hostname: mgmtnode

    networks:
      internal:
        ipv4_address: ${SUBNET}.1.1
        ipv6_address: ${SUBNET6}:1:1
      stark_stark:

    volumes:
      - root-home:/root
      - home:/home/
      - slurmctld:/var/spool/slurm
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - auth:/auth/
      - src:/usr/local/src/

      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/

      - /var/run/docker.sock:/var/run/docker.sock

      - munge:/etc/munge


      - tmp_mgmtnode:/tmp
      - run_mgmtnode:/run
      - run-lock_mgmtnode:/run/lock
      - journal_mgmtnode:/var/lib/journal

      - cluster-cfg:${CLUSTER_CONFIG_INNER_FOLDER}


    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "slurmdbd"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  login:

    image: stark/scaleout:latest

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET6}:"
      - container=docker

    hostname: login

    networks:
      internal:
        ipv4_address: ${SUBNET}.1.5
        ipv6_address: ${SUBNET6}:1:5

    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - home:/home/
      - slurmctld:/var/spool/slurm
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/
      - /dev/fuse:/dev/fuse:rw
      - container-shared:/srv/containers

      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/

      - /var/run/docker.sock:/var/run/docker.sock


      - tmp_login:/tmp
      - run_login:/run
      - run-lock_login:/run/lock
      - journal_login:/var/lib/journal

      - cluster-cfg:${CLUSTER_CONFIG_INNER_FOLDER}
      

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  node00:

    image: stark/scaleout:latest

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET6}:"
      - NODE_NAME=${NODE00_NAME}
      - NODE_IP4=${NODE00_IP4}
      - NODE_IP6=${NODE00_IP6}
      - container=docker

    hostname: node00

    networks:
      internal:
        ipv4_address: ${NODE00_IP4}
        ipv6_address: ${NODE00_IP6}

    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - home:/home/
      - /dev/log:/dev/log
      - mail:/var/spool/mail/
      - src:/usr/local/src/
      - container-shared:/srv/containers

      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/

      - /var/run/docker.sock:/var/run/docker.sock


      - tmp_node00:/tmp
      - run_node00:/run
      - run-lock_node00:/run/lock
      - journal_node00:/var/lib/journal

      - cluster-cfg:${CLUSTER_CONFIG_INNER_FOLDER}


    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  openondemand:

    build:
      context: ./openondemand
      network: host

    image: stark/openondemand

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET6}:"
      - DEFAULT_SSHHOST=login

    volumes:
      - /dev/log:/dev/log
      - etc-ssh:/etc/shared-ssh
      - home:/home/

    networks:
      internal:
        ipv4_address: ${SUBNET}.1.21
        ipv6_address: ${SUBNET6}:1:21

    depends_on:
      - "login"

    ports:
      - 8081:80

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined


  rest:

    hostname: rest

    image: stark/scaleout:latest

    networks:
      internal:
        ipv4_address: ${SUBNET}.1.6
        ipv6_address: ${SUBNET6}:1:6
      stark_stark:

    volumes:
      - etc-ssh:/etc/ssh
      - etc-slurm:/etc/slurm
      - /dev/log:/dev/log

      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro

      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro

      - /sys/fs/fuse/:/sys/fs/fuse/

      - /var/run/docker.sock:/var/run/docker.sock


      - tmp_rest:/tmp
      - run_rest:/run
      - run-lock_rest:/run/lock
      - journal_rest:/var/lib/journal

      - cluster-cfg:${CLUSTER_CONFIG_INNER_FOLDER}

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"



  proxy:

    build:
      context: ./proxy
      network: host

    image: stark/proxy:latest

    environment:
      - SUBNET="${SUBNET}"
      - SUBNET6="${SUBNET6}:"
      - container=docker

    hostname: proxy

    command: ["bash", "-c", "nginx & php-fpm8 -F"]

    networks:
      internal:
        ipv4_address: ${SUBNET}.1.7
        ipv6_address: ${SUBNET6}:1:7

    volumes:
      - auth:/auth/
      - /dev/log:/dev/log

    tty: true

    logging:
      driver: local

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    ports:
      - 8080:8080

    depends_on:
      - "rest"

    extra_hosts:
      - "db:${SUBNET}.1.3"
      - "db:${SUBNET6}:1:3"
      - "slurmdbd:${SUBNET}.1.2"
      - "slurmdbd:${SUBNET6}:1:2"
      - "mgmtnode:${SUBNET}.1.1"
      - "mgmtnode:${SUBNET6}:1:1"
      - "login:${SUBNET}.1.5"
      - "login:${SUBNET6}:1:5"
      - "rest:${SUBNET}.1.6"
      - "rest:${SUBNET6}:1:6"
      - "proxy:${SUBNET}.1.7"
      - "proxy:${SUBNET6}:1:7"
      - "openondemand:${SUBNET}.1.21"
      - "openondemand:${SUBNET6}:1:21"

