##########################################################################
# Config Yaml Version:     1
# Description:             Yaml file to run rdraw snakefile module
##########################################################################

# DEV version 1 : 23/11/2022
# Authoring : Thomas LAVAUX

##########################################################################
# Add here variables that will extend default configuration yaml file.
# If a variable was already defined in the default configuration yaml file, it will be replace.
# launch snakemake -s snakefile_decon -c(numberofthreads) --config run=absolutepathoftherundirectory var1=0.05 var2=12
# separate multiple variable with a space
################## Directories and variables ##################
# Name of the submodule = {serviceName} from listener.py/launcher.py
serviceName: "DRAWFUSIONS"
# Name of the module
module: "rnaseq"
# Databases folder
databases: "databases"
# Service folder
services: "services"
# Config folder
config: "config"
# Specify a DATE_TIME value (for rerun)
DATE_TIME: ""
# Output directory
OUTPUT_DIR: ""
# Other path to copy results, leave empty to not copy, add a path to copy to this folder
# Replace by "depository" will copy the results in a second folder based on OUTPUT_DIR, replacing "repository" with "depository" if repository exist
DEPOT_DIR: "depository"
# Default path to the input datas == {run} from listener.py/launcher.py
run: ""

# Bed file
BED_FILE: ""
# Genes file
GENES_FILE: ""
# Transcripts file
TRANSCRIPTS_FILE: ""
# List genes
LIST_GENES: ""

# Files to index into the dictionary depending on extension (endwith)
EXT_INDEX_LIST: [".transcripts",".genes.bed",".design.bed",".list.genes",".tag",".bam",".arriba.fusions.tsv"]
# List of files extension to process
PROCESS_FILE: ['.bam', 'bam.bai', '.arriba.fusions.tsv']
# How to copy input files (bam, bai, cram) : ln or leave empty (it will rsync files or index for bai from bam)
PROCESS_CMD: 'ln'
# Only analyse bam/cram files named *.validation.bam or *.validation.cram
VALIDATION_ONLY: False
# Insert an aligner name to the bam/cram file name (from sample.bam to sample.aligner_name.bam)
ALIGNER_NAME:

# Samples list exclusion (not to be analysed) ; exclude if startwith, case insensitive
EXCLUDE_SAMPLE: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC']
# Sample filter
FILTER_SAMPLE: []

# Extension files to copy after pipeline success
# using brace extension, remove space between extensions
INCLUDE_RSYNC: "{'*.pdf','*/'}"
# Extensions files to copy after pipeline failure
INCLUDE_LOG_RSYNC: "{'*.log','*.err','*Failed.txt'}"

##### Search parameters of input for the search function #####
RECURSIVE_SEARCH: False
SEARCH_ARGUMENT: ["/*/STARK/*"]

# Path of the template (template is template.html)
TEMPLATE_DIR: "/app/template"
# For result html report, list of extensions to report
RESULT_EXT_LIST: ['.pdf']

# LOG level 30=logging.WARNING or 20=logging.INFO
LOG_LEVEL: 30
# Command to download (wget or aria2c)
COMMAND: "aria2c --async-dns=false -c -s 16 -x 16 -k 1M -j 1"

############## Tools specific parameters ##############
# List of tools used to generate fusion analysis
FUSION_TOOL: ['arriba', 'starfusion']
### TOOLS PATH ###
# Default path to a FASTA file with .fasta reference genome (hg19/hg38 for ex)
REFGENEFA_PATH: "/databases/genomes/current/hg19.fa"
# GTF file (Gencode)
REFGTFGENCODE_PATH: "/databases/gencode/current/gencode.v19.annotation.gtf_withproteinids"
# Arriba specifics databases (default is /opt/conda/var/lib/arriba)
REFPROTDOMAIN_PATH: "/databases/arriba/current/protein_domains_hg19_hs37d5_GRCh37_v2.4.0.gff3"
REFCYTOBAND_PATH: "/databases/arriba/current/cytobands_hg19_hs37d5_GRCh37_v2.4.0.tsv"
ARRIBA_SCRIPTS: "/app/scripts"