#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # EDITH Dashboard
    stark-module-interfaces-submodule-edith-service-dashboard:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_ENV_FILE}
        environment:
            - FOLDER_SERVICES=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_SERVICES}
            - FOLDER_INPUTS=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_INPUTS}
            - FOLDER_REPOSITORIES=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_REPOSITORIES}
            - SUBFOLDER_SERVICE_EDITH=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_SUBFOLDER_SERVICE_EDITH}
            - FOLDER_INDEXES=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_INDEXES}
            - FOLDER_API=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_API}
            - FOLDER_LISTENER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_LISTENER}
            - FOLDER_IGV=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_IGV}
            - URI_API=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_URI_API}
            - DOCKER_STARK_PREFIX=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_DOCKER_STARK_PREFIX}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_TARGET}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_INNER_FOLDER_SERVICES}:rw
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_SERVICES}:rw
            # Services
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_SERVICES}:rw
            # Databases
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}:ro
            # Input
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_INPUTS}/Input:ro
            # Output
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_REPOSITORIES}/Repository:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_REPOSITORIES}/Archives:ro
        networks:
            - stark_stark



# NETWORK
###########

networks:
    stark_stark:
        external: true
