#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # DEJAVU listener
    stark-module-databases-submodule-dejavu-service-listener:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_CONTEXT_DOCKERFILE}
            args:
                STARK_IMAGE: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_BUILD_ARGS_STARK_IMAGE}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_COMMAND}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENV_FILE}
        environment:
            - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_SLEEP}
            - DEJAVU_SUBFOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_SUBFOLDER}
            - DEJAVU_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_FOLDER}
            - REPO_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_REPO_FOLDER}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_SERVICES}:rw
            # DEJAVU folder
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_SERVICE_DATABASES_DEJAVU_listener_DATABASE_subfolder}:${DOCKER_STARK_INNER_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_SUBFOLDER}:rw
            # Repository folders
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:ro
        networks:
            - stark_stark



# NETWORK
###########

networks:
    stark_stark:
        external: true
