#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # DEJAVU setup
    stark-module-databases-submodule-dejavu-service-setup:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE_CONTEXT_DOCKERFILE}
            args:
                STARK_IMAGE: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_IMAGE_BUILD_ARGS_STARK_IMAGE}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_COMMAND}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONTAINER_ENV_FILE}
        environment:
            - SETUP_CONFIG_LISTENER_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_INNER_FOLDER_SETUP_LISTENER_CONFIG}
            - SETUP_CONFIG_DASHBOARD_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_INNER_FOLDER_SETUP_DASHBOARD_CONFIG}
        volumes:
            # Listener config
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG}:rw
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_HOST_FOLDER_SETUP_LISTENER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONFIG_LISTENER_FOLDER}:ro
            # Dashboard config
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_CONFIG}:rw
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_HOST_FOLDER_SETUP_DASHBOARD_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_SETUP_CONFIG_DASHBOARD_FOLDER}:ro
        networks:
            - stark_stark


    # DEJAVU listener
    stark-module-databases-submodule-dejavu-service-listener:
        depends_on: 
            - stark-module-databases-submodule-dejavu-service-setup
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_COMMAND}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENV_FILE}
        environment:
            - APPLICATION=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_APPLICATION}
            - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_SLEEP}
            - DEJAVU_SUBFOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_SUBFOLDER}
            - DEJAVU_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_FOLDER}
            - REPO_FOLDER=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_REPO_FOLDER}
            - SAMPLE_EXCLUDE_FILE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_SAMPLE_EXCLUDE_FILE}
            - GROUP_PROJECT_LIST_FILE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_GROUP_PROJECT_LIST_FILE}
            - GROUP_PROJECT_FILTER_FILE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_GROUP_PROJECT_FILTER_FILE}
            - RELEASE_SYMLINK=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_RELEASE_SYMLINK}
            - PREVIOUS_RELEASE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_PREVIOUS_RELEASE}
            - PREVIOUS_COPY_MODE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_PREVIOUS_COPY_MODE}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_SERVICES}:rw
            # DEJAVU folder
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_SERVICE_DATABASES_DEJAVU_listener_DATABASE_subfolder}:${DOCKER_STARK_INNER_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DEJAVU_SUBFOLDER}:rw
            # Repository folders
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:ro
        networks:
            - stark_stark


    # Databases Dashboard
    stark-module-databases-submodule-dejavu-service-dashboard:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_ENV_FILE}
        environment:
            - FOLDER_DATABASES=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}
            - DOCKER_STARK_PREFIX=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_DOCKER_STARK_PREFIX}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_TARGET}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_SERVICES}:rw
            # Services
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_SERVICES}:rw
            # Databases
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PUBLIC_DIR}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}:ro
        networks:
            - stark_stark


# NETWORK
###########

networks:
    stark_stark:
        external: true
