# Global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  scrape_timeout: 15s 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
    - targets: ['172.43.5.0:9100']

