#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # IGV
    stark-module-genomebrowser-submodule-igv-service-igv:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_IMAGE}
        #build:
        #    context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_IMAGE_CONTEXT}
        #    dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_CONTAINER_ENV_FILE}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_PARAM_PORT_TARGET}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_IGV_INNER_FOLDER_SERVICES}:rw
        networks:
            - stark_stark



# NETWORK
###########

networks:
    stark_stark:
        external: true
