#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:

    # CLOUDGENE Dashboard
    stark-module-interfaces-submodule-cloudgene-service-dashboard:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE}
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_IMAGE_CONTEXT_DOCKERFILE}
            args:
                - STARK_IMAGE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_STARK_IMAGE}
                - CLOUDGENE_RELEASE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_CLOUDGENE_RELEASE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_CONTAINER_RESTART}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_PORT_TARGET}
        volumes:
            # Docker sock
            - ${DOCKER_STARK_SOCK_MOUNT}
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_CONFIG}:rw
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_INNER_FOLDER_SERVICES}:rw
            # Databases
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_DATABASES}:ro
            # Input
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_INPUTS}/Input:ro
            # Output
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_REPOSITORIES}/Repository:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_INNER_FOLDER_DATA}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_DASHBOARD_PARAM_FOLDER_REPOSITORIES}/Archives:ro
        networks:
            - stark_stark

# NETWORK
###########

networks:
    stark_stark:
        external: true
