{
  "submodules": {
    "canoes": {
      "description" : "CANOES analysis for CNV (Copy Number Variation)",
      "services": {
        "cli": {
          "code": "cli",
          "name": "CLI service",
          "type": "CLI",
          "description": "cli service, create image and configure service.",
          "release": "1.0",
          "available": false
        },
        "listener": {
          "code": "listener",
          "name": "LISTENER service",
          "type": "listener",
          "description": "listener service, create image and configure service.",
          "release": "1.0",
          "available": false
        }
      }
    }
  }
}
