#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:

  # cli
  stark-module-structuralvariation-submodule-canoes-service-cli:
    image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
    build:
      context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT}
      dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT_DOCKERFILE}
    container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_NAME}
    restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_RESTART}
    entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENTRYPOINT}
    command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_COMMAND}
    environment:
      - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_SLEEP}
      - DOCKER_MODULE_STRUCTURALVARIATION_SUBMODULE_CANOES_FOLDER_REPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}
      - DOCKER_MODULE_STRUCTURALVARIATION_SUBMODULE_CANOES_FOLDER_DEPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}
    volumes:
      # Main configuration
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_INNER_FOLDER_DATA}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_CONFIG}:ro
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_SERVICES}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_ANNOTSV_HOST_PATTERN}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_ANNOTSV_INNER}:ro
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/AnnotSV/current/Annotations_Human:/tools/AnnotSV/3.1/share/AnnotSV/Annotations_Human:rw
      - /home1/TOOLS/tools/toolkit/current/lib:/toolkit:ro
      - /home1/L/NGS/Qualite/Sets_de_validation/SET_CNV/SET_CNV_POUR_VALIDATION:/datasets:ro
      #- /home1/L/NGS/Qualite/Preuves_validation/modules/canoes:/validationcanoes:rw
      - ${DOCKER_STARK_SOCK_MOUNT}
    networks:
      - ${DOCKER_STARK_MAIN_NETWORK}

  # listener
  stark-module-structuralvariation-submodule-canoes-service-listener:
    image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE}
    container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_NAME}
    entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENTRYPOINT}
    command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_COMMAND}
    restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_RESTART}
    environment:
      - MICROSERVICE_IMAGE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
      - MICROSERVICE_MONTAGE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_CONTAINER_MOUNT} -e DOCKER_MODULE_STRUCTURALVARIATION_SUBMODULE_CANOES_FOLDER_REPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY} -e DOCKER_MODULE_STRUCTURALVARIATION_SUBMODULE_CANOES_FOLDER_DEPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}
      - MICROSERVICE_LAUNCH=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_MICROSERVICE_LAUNCH}
      - MICROSERVICE_NAME=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_MICROSERVICE_NAME}
      - MICROSERVICE_CONFIG=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_CONFIG}
      - MICROSERVICE_APP_CONFIG=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_APP_CONFIG}
      - MICROSERVICE_REPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}
      - JSON=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_JSON}
      - CONTAINERFILE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_SERVICES}
      - DAEMON_RUN_EXISTENCE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DAEMON_RUN_EXISTENCE}
      - DAEMON_DELAY=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_DAEMON_DELAY}
    volumes:
      # Main configuration
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
      - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG}:ro
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_SERVICES}:rw
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG_LAUNCHER}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG_LAUNCHER}:rw
      #- ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}/OMIMannotations/current/:/tools/AnnotSV/2.1/Annotations/Genes-based/OMIM/:rw
      - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_INNER_FOLDER_CONFIG}:ro #config cli available in listener container
      - ${DOCKER_STARK_SOCK_MOUNT}
    networks:
      - ${DOCKER_STARK_MAIN_NETWORK}

# NETWORK
###########

networks:

  stark_stark:
    external: true
