OLD_BED: True
plot: All
DEPOT_COPY: True
INCLUDE_RSYNC: "{'*Design.vcf.gz','*Design.vcf.gz.tbi','*Design.tsv','*Design_results_all.txt','*Identify_Failures.txt','*.pdf','*/'}"
EXCLUDE_SAMPLE: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC', 'Blc']
