##########################################################################
# Config Yaml Version:     0.1
# Description:             Yaml file to run Snakefile SCRAMBLE module
##########################################################################
# DEV version 0.1 : 10/11/2021
# INT version 0.1 : 17/03/2022
# PROD version 1 : 03/06/2022
# Authoring : Thomas LAVAUX
# Add here variables that will extend default configuration yaml file.
# If a variable was already defined in the default configuration yaml file, it will be replace.
# launch snakemake -s snakefile_decon -c(numberofthreads) --config run=absolutepathoftherundirectory var1=0.05 var2=12
# separate multiple variable with a space
################## Directories and variables ##################

# Name of the module = {serviceName} from listener.py/launcher.py
serviceName: "SCRAMBLE"

# Default repository/depository path for STARK directories structure
repository: "/STARK/output/repository"
depository: "/STARK/output/depository"
# Output directory if not repository
OUTPUT_DIR: ""
# Copy to depot directory (archive)
DEPOT_COPY: True

# Group and App default name
GROUP_NAME: "UNKNOWN"
APP_NAME: "UNKNOWN"

# Default path to the input datas == {run} from listener.py/launcher.py
run: ""
# Bed file
BED_FILE: ""
# Genes file
GENES_FILE: ""
# Transcripts file
TRANSCRIPTS_FILE: ""
# List genes
LIST_GENES: ""

# Path to scripts
SCRIPTS_PATH: "/app/scripts"
# Samples list exclusion (not to be analyse) ; exclude if startwith, case insensitive
EXCLUDE_SAMPLE: ['POOL_', 'BlcADN', 'blanc', 'BlcPCR', 'blcPCR', 'Z_NTC', 'NTC', 'Blc']
# Sample filter
FILTER_SAMPLE: []

### Indexing files options
# Ext to index (endwith)
EXT_INDEX_LIST: [".cram", ".cram.crai", ".transcripts", ".genes.bed", ".design.bed", ".bam", ".bam.bai", ".list.genes"]
# Process .bam or .cram
PROCESS_FILE: [".bam"]
# Process input files : cram/cp/rsync/ls/filterbam
PROCESS_CMD: 'cp'
# Only analyse validation.bam/cram files
VALIDATION_ONLY: False
# Append an aligner name if missing (from sample.bam to sample.aligner_name.bam)
ALIGNER_NAME:

# Rsync option for copy
# include_rsync must have more than one arguement
INCLUDE_RSYNC: "{'*Full.vcf.gz','*Full.vcf.gz.tbi','*Design.vcf.gz','*Design.vcf.gz.tbi','*AnnotSV.Full.tsv','*AnnotSV.Design.tsv'}"
# exclude_rsync can only take on arguement
EXCLUDE_RSYNC: "'*'"
# for log file copy if pipeline failed
INCLUDE_LOG_RSYNC: "{'*.log','*.err','*Failed.txt'}"

##### Search parameters for inputs ####
RECURSIVE_SEARCH: False
SEARCH_ARGUMENT: "/*/STARK/*"
## DEBUG ##
DEBUG_MODE: False
# MISC
THREADS: "4"

# Option to filter vcf with bcftools
# ex "-i 'FORMAT/DP>=30 && FORMAT/VAF>=0.01'"
BCFTOOLS_FILTER: ""
################## Tools specific parameters ##################
# Default path to a FASTA file with .fasta reference genome (hg19/hg38 for ex)
REFGENEFA_PATH: "/STARK/databases/genomes/current/hg19.fa"
# Path to Scramble R directory scripts
SCRAMBLE_PATH: "/opt/conda/share/scramble/bin"
DUMMY_PATH: "/app/scripts/dummy"
################## cluster_identifier params
m: 10 # min soft clipped bases to be put in a cluster (default 10)
s: 5 # min soft clipped reads to be a cluster (default 5)
r: all # region (default all : format ex chr9:1-20000)

################## scramble params
nCluster: 5 # min cluster size to analyze(default 5)
mei-score: 50 # min MEI alignment score to call (default 50)
poly-a-frac: 0.75 # fraction of clipped length for calling polyA tail in MEIs (default 0.75)
poly-a-dist: 100 # how far from MEI to look for polyA tail (default 100)
# choose to evaluate meis or deletions
# --eval-meis / --eval-dels
scramble_mode: "--eval-dels"
# Default path to an FASTA file with MEI Ref sequences
REFMEI_PATH: "/opt/conda/share/scramble/resources/MEI_consensus_seqs.fa"

################## AnnotSV params
hpo: # HPO terms list describing the phenotype of the individual being investigated Values: use comma, semicolon or space separated class values Default = "" (e.g.: "HP:0001156,HP:0001363,HP:0011304") = only for individual analysis
genomeBuild: GRCh37 # GRCh38 default, set to GRCh37 for hg19
overlap: 100 # default 100
annotationMode: full # split, full or both (defaut both)
annotationdir: "/STARK/databases/AnnotSV/3.1/" # path to the annotation database (3.3.6)