{
  "submodules": {
    "fusions": {
      "description" : "fusions",
      "services": {
        "cli": {
          "code": "cli",
          "name": "CLI service",
          "type": "Cli",
          "description": "cli service, create image and configure service.",
          "release": "1.0",
          "available": false
        },
        "listener": {
          "code": "listener",
          "name": "LISTENER service",
          "type": "listener",
          "description": "listener service, create image and configure service.",
          "release": "2.0",
          "available": false
		},
		"setup": {
          "code": "setup",
          "name": "SETUP service",
          "type": "setup",
          "description": "setup service, create image and configure service.",
          "release": "1.0",
          "available": false
        }
      }
    }
  }
}
