###############################
# Docker compose FLT3ITDEXT  #
###############################
version: '3.9'

services:

    stark-module-structuralvariation-submodule-flt3itdext-service-setup:
        image: stark/stark-module-structuralvariation-submodule-flt3itdext-service-common:1.0
        build:
            context: ./
            dockerfile: flt3itdext_dockerfile
        entrypoint: "snakemake"
        command: "-p -s /app/bin/flt3itdext_setup.smk"
        container_name: stark-module-structuralvariation-submodule-flt3itdext-service-setup
        restart: "no"
        volumes:
            - /home1/data/STARK/services/structuralvariation/flt3itdext:/services/structuralvariation/flt3itdext:rw
            - /home1/data/STARK/config/structuralvariation/flt3itdext:/config/structuralvariation/flt3itdext:rw
            - /home1/data/STARK/databases:/databases:rw
        working_dir: /
        networks:
            - stark_stark

    stark-module-structuralvariation-submodule-flt3itdext-service-cli:
        image: stark/stark-module-structuralvariation-submodule-flt3itdext-service-common:1.0
        build:
            context: ./
            dockerfile: flt3itdext_dockerfile
        container_name: stark-module-structuralvariation-submodule-flt3itdext-service-cli
        restart: "no"
        entrypoint: ["/bin/bash"]
        command: ["-l"]
        tty: true
        stdin_open: true
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:rw
            - /home1/data/STARK/output/depository:/output/depository:rw
            - /home1/data/STARK/services/structuralvariation/flt3itdext/cli:/services/structuralvariation/flt3itdext/cli:rw
            - /home1/data/STARK/config/structuralvariation/flt3itdext/cli:/config/structuralvariation/flt3itdext/cli:ro
            - /home1/data/STARK/databases:/databases:ro
        networks:
            - stark_stark
        healthcheck:
            test:
                [
                    "CMD",
                    "test",
                    "-f",
                    "/services/structuralvariation/flt3itdext/cli/SETUPComplete.txt"
                ]
            timeout: 10s
            interval: 30s
            retries: 30
 
 
    stark-module-structuralvariation-submodule-flt3itdext-service-listener:
        image: stark/stark-module-common-submodule-listener-service-listener:2.0
        container_name: stark-module-structuralvariation-submodule-flt3itdext-service-listener
        entrypoint: "python3"
        command: "/app/bin/listener.py --input=/output/repository --json=/config/structuralvariation/flt3itdext/listener/flt3itdext.json --config=/config/structuralvariation/flt3itdext/listener/flt3itdext.conf --servicename=FLT3ITDEXT --containersfile=/services/structuralvariation/flt3itdext/listener --nbDaysBack=30 --minDelay=1"
        restart: always
        environment:
            - DOCKER_STARK_MODULE_SUBMODULE_INNER_FOLDER_CONFIG=/config/structuralvariation/flt3itdext
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:ro
            - /home1/data/STARK/output/depository:/output/depository:ro
            - /home1/data/STARK/services/structuralvariation/flt3itdext:/services/structuralvariation/flt3itdext:rw
            - /home1/data/STARK/config/structuralvariation/flt3itdext:/config/structuralvariation/flt3itdext:ro
            - /home1/data/STARK/config/structuralvariation/flt3itdext/listener/launcher.py:/app/bin/config/launcher.py:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - stark_stark
        depends_on:
            stark-module-structuralvariation-submodule-flt3itdext-service-cli:
                condition: service_healthy

networks:
    stark_stark:
        external: true