{
  "submodules": {
    "cqi": {
      "description": "SubModule CQI including CLI and listener services",
      "services": {
        "cli": {
          "code": "cli",
          "name": "CQI cli",
          "type": "CLI",
          "description": "A CQI CLI.",
          "release": "1.0",
          "available": true
        },
        "listener": {
          "code": "listener",
          "name": "CQI listener",
          "type": "listener",
          "description": "A CQI listener service is started as a daemon, listening for new STARK analyzed run (new folder in output/repository) and well configured (STARKComplete.txt without CQIRunning.txt or CQIComplete.txt), and check triggers to launch or not analysis.",
          "release": "1.0",
          "available": true
        }
      }
    }
  }
}
