#########
# STARK #
#########
# Usage: docker-compose up

version: '3'



# SERVICES
##########

services:


    # NETDATA
    stark-module-admin-submodule-netdata-service-netdata:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_IMAGE}
        #command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_CONTAINER_COMMAND}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_CONTAINER_NAME}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_CONTAINER_ENV_FILE}
        ports:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_PORT_PUBLISHED}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_PORT_TARGET}
        hostname: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_HOSTNAME}
        cap_add:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_CAP_ADD}
        security_opt:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_SECURITY_OPT}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_SOCK_MOUNT}:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            # Drives
            # Inputs
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_INPUT}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT_RUNS}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_INPUT_RUNS}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT_MANIFESTS}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_INPUT_MANIFESTS}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT_PEDIGREE}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_INPUT_PEDIGREE}
            # Repositories
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_FAVORITES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_FAVORITES}
            # Output (other)
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_RESULTS}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_RESULTS}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEMULTIPLEXING}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEMULTIPLEXING}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_TMP}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_OUTPUT_TMP}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_DATA}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_DATABASES}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_CONFIG}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG_MYAPPS}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_CONFIG_MYAPPS}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG_HOWARD}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_CONFIG_HOWARD}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_SERVICES}
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SOURCES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_NETDATA_PARAM_MOUNT_HOME}/${DOCKER_STARK_INNER_FOLDER_SOURCES}
        networks:
            - stark_stark



# NETWORK
###########

networks:
    stark_stark:
        external: true
