services:

    stark-module-multisampleanalysis-submodule-pool-service-cli:
        image: ${DOCKER_STARK_SERVICE_IMAGE_REGISTRY}stark-module-multisampleanalysis-submodule-pool-service-cli:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_TAG}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                STARK_MAIN_FOLDER: ${DOCKER_STARK_MAIN_FOLDER}
        container_name: stark-module-multisampleanalysis-submodule-pool-service-cli
        restart: no
        entrypoint: /bin/bash
        stdin_open: true # docker run -i (interactive stdin)
        tty: true # docker run -t (pseudo-TTY)
        volumes:
            - ${DOCKER_STARK_MAIN_FOLDER}/output:/STARK/output:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:/STARK/output/repository:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:/STARK/output/depository:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:/STARK/output/archives:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:/STARK/data:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:/STARK/databases:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_CONFIG}:/STARK/config/multisampleanalysis/pool/cli:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_HOST_FOLDER_SERVICES}:/STARK/services/multisampleanalysis/pool/cli:rw
            - ${DOCKER_STARK_SOCK_MOUNT}
            - /dev/shm/pools:/dev/shm/pools:rw
            # for dev
            - /home1/bin/STARK-modules/current/services/multisampleanalysis/pool/src:/app/src:rw
        networks:
            - ${DOCKER_STARK_MAIN_NETWORK}

    # this service is designed to run once when the compose is launched then exit
    stark-module-multisampleanalysis-submodule-pool-service-setup:
        image: ${DOCKER_STARK_SERVICE_IMAGE_REGISTRY}stark-module-multisampleanalysis-submodule-pool-service-cli:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_TAG}
        # if the files launcher.py and pool.json do not exist in the config folder, copy them from the image to the config folder
        command: bash -c 'for file in launcher.py pool.json; do if [ ! -f "/config/$$file" ]; then cp "/app/config/$$file" "/config/"; fi; done'
        volumes:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:/config:rw
        depends_on:
            - stark-module-multisampleanalysis-submodule-pool-service-cli
        networks:
            - ${DOCKER_STARK_MAIN_NETWORK}

    stark-module-multisampleanalysis-submodule-pool-service-listener:
        image: ${DOCKER_STARK_SERVICE_IMAGE_REGISTRY}stark-module-common-submodule-listener-service-listener:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_TAG}
        container_name: stark-module-multisampleanalysis-submodule-pool-service-listener
        command: python3 /app/bin/listener.py --input=/STARK/output/repository --json /STARK/config/multisampleanalysis/pool/listener/pool.json --servicename=POOL --containersfile=/STARK/services --nbDaysBack=60 --minDelay=1
        restart: always
        environment:
            - MICROSERVICE_IMAGE=${DOCKER_STARK_SERVICE_IMAGE_REGISTRY}stark-module-multisampleanalysis-submodule-pool-service-cli:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_TAG}
            - MICROSERVICE_MONTAGE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_PARAM_CONTAINER_MOUNT}
            - MICROSERVICE_LAUNCH=/opt/conda/envs/py312/bin/python /app/src/wrapper.py -g /STARK/databases/genomes/current/${GENOME}/${GENOME}.fa
            - MICROSERVICE_REPOSITORY=${DOCKER_STARK_MAIN_FOLDER}/output/repository
            - PYTHONUNBUFFERED=1
        volumes:
            - ${DOCKER_STARK_MAIN_FOLDER}/output:/STARK/output:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:/STARK/output/depository:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:/STARK/output/archives:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:/STARK/databases:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:/STARK/config/multisampleanalysis/pool/listener:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_SERVICES}:/STARK/services/multisampleanalysis/pool/listener:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/config/multisampleanalysis/pool/listener/launcher.py:/app/bin/launcher.py:ro
            - ${DOCKER_STARK_SOCK_MOUNT}
        depends_on:
            - stark-module-multisampleanalysis-submodule-pool-service-setup
        networks:
            - ${DOCKER_STARK_MAIN_NETWORK}

networks:
    stark_stark:
        external: true
