########################
# Docker compose DECON #
########################
version: '3'

services:

    stark-module-structuralvariation-submodule-decon-service-setup:
        image: stark/stark-module-structuralvariation-submodule-decon-service-common:3.0
        build:
            context: ./
            dockerfile: decon_dockerfile
        entrypoint: "python3"
        command: "/app/bin/setup.py"
        container_name: stark-module-structuralvariation-submodule-decon-service-setup
        restart: "no"
        environment:
            - DOCKER_STARK_MODULE_SUBMODULE_NAME=decon
            - DOCKER_STARK_MODULE_NAME=structuralvariation
            - DOCKER_STARK_INNER_FOLDER_DATABASES=/STARK/databases
            - DOCKER_STARK_INNER_FOLDER_SERVICES=/STARK/services
            - DOCKER_STARK_INNER_FOLDER_CONFIG=/STARK/config
        volumes:
            - /home1/data/STARK/services/structuralvariation/decon:/STARK/services/structuralvariation/decon:rw
            - /home1/data/STARK/config/structuralvariation/decon:/STARK/config/structuralvariation/decon:rw
            - /home1/data/STARK/databases:/STARK/databases:rw
        networks:
            - stark_stark

    stark-module-structuralvariation-submodule-decon-service-cli:
        image: stark/stark-module-structuralvariation-submodule-decon-service-common:3.0
        build:
            context: ./
            dockerfile: decon_dockerfile
        container_name: stark-module-structuralvariation-submodule-decon-service-cli
        restart: "no"
        entrypoint: [ "/bin/bash", "-l", "-c" ]
        command: "'while true; do sleep 60; done'"
        volumes:
            - /home1/data/STARK/output/repository:/STARK/output/repository:rw
            - /home1/data/STARK/output/depository:/STARK/output/depository:rw
            - /home1/data/STARK/services/structuralvariation/decon/cli:/STARK/services/structuralvariation/decon/cli:rw
            - /home1/data/STARK/config/structuralvariation/decon/cli:/STARK/config/structuralvariation/decon/cli:ro
            - /home1/data/STARK/databases:/STARK/databases:ro
            - /home1/data/STARK/databases/OMIMannotations/current:/STARK/databases/AnnotSV/3.3.6/Annotations_Human/Gene-based/OMIM:ro
            - /home1/data/STARK/databases/AnnotSV/3.3.6:/STARK/databases/AnnotSV/3.3.6:rw
        networks:
            - stark_stark
        healthcheck:
            test:
                [
                    "CMD",
                    "test",
                    "-f",
                    "/STARK/services/structuralvariation/decon/cli/SETUPComplete.txt"
                ]
            timeout: 10s
            interval: 60s
            retries: 30

    stark-module-structuralvariation-submodule-decon-service-listener:
        image: stark/stark-module-common-submodule-listener-service-listener:2.0
        container_name: stark-module-structuralvariation-submodule-decon-service-listener
        entrypoint: "python3"
        command: "/app/bin/listener.py --input=/STARK/output/repository --json=/STARK/config/structuralvariation/decon/listener/decon.json --config=/STARK/config/structuralvariation/decon/listener/decon.conf --servicename=DECON --containersfile=/STARK/services/structuralvariation/decon/listener --nbDaysBack=30 --minDelay=1"
        restart: always
        environment:
            - DOCKER_STARK_MODULE_SUBMODULE_INNER_FOLDER_CONFIG=/STARK/config/structuralvariation/decon
        volumes:
            - /home1/data/STARK/output/repository:/STARK/output/repository:ro
            - /home1/data/STARK/output/depository:/STARK/output/depository:ro
            - /home1/data/STARK/services/structuralvariation/decon:/STARK/services/structuralvariation/decon:rw
            - /home1/data/STARK/config/structuralvariation/decon:/STARK/config/structuralvariation/decon:ro
            - /home1/data/STARK/config/structuralvariation/decon/listener/launcher.py:/app/bin/config/launcher.py:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - stark_stark
        depends_on:
            stark-module-structuralvariation-submodule-decon-service-cli:
                condition: service_healthy

networks:
    stark_stark:
        external: true