#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES #
############

services:

    # cli
    stark-module-variantannotation-submodule-varank-service-cli:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
        # depends_on: stark-module-variantannotation-submodule-varank-service-service-setup
        build:
            context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT}
            dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_NAME}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_COMMAND}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_CONTAINER_ENV_FILE}
        environment:
            - SLEEP=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_PARAM_SLEEP}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_MODULE_NAME=${DOCKER_STARK_MODULE_NAME}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_SUBMODULE_NAME=${DOCKER_STARK_MODULE_SUBMODULE_NAME}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_SERVICES=${DOCKER_STARK_INNER_FOLDER_SERVICES}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_ARCHIVES=${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_REPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_CONFIG=${DOCKER_STARK_INNER_FOLDER_CONFIG}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_DEPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}
            - DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_DATABASES=${DOCKER_STARK_INNER_FOLDER_DATABASES}
        volumes:
        # Volumes for generating, deposing and archiving results
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:rw
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_INNER_FOLDER_SERVICES}:rw
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_INNER_FOLDER_DATA}:rw
        # Volumes for VaRank configuration and licence
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG}:${DOCKER_STARK_INNER_FOLDER_CONFIG}:rw
        # Volumes for databases
        - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
        # File for developing, to comment if not used
        #- /home1/bin/STARK-modules/current/services/variantannotation/varank/cli/dockerfile/bin/newVaRank.py:/tools/varank/current/scripts/newVaRank.py:rw
        networks: 
            - ${DOCKER_STARK_MAIN_NETWORK}

    # listener
    stark-module-variantannotation-submodule-varank-service-listener:
        image: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE}
        # build:
        # context: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_CONTEXT}
        # dockerfile: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_IMAGE_CONTEXT_DOCKERFILE}
        container_name: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_NAME}
        entrypoint: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENTRYPOINT}
        command: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_COMMAND}
        restart: ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_RESTART}
        env_file:
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENV_FILE}
        environment:
            - MICROSERVICE_IMAGE=${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_CLI_IMAGE}
            - MICROSERVICE_MONTAGE=--env-file ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENV_FILE} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_MODULE_NAME=${DOCKER_STARK_MODULE_NAME} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_SUBMODULE_NAME=${DOCKER_STARK_MODULE_SUBMODULE_NAME} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_SERVICES=${DOCKER_STARK_INNER_FOLDER_SERVICES} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_ARCHIVES=${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_REPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_CONFIG=${DOCKER_STARK_INNER_FOLDER_CONFIG} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_DEPOSITORY=${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_DATABASES=${DOCKER_STARK_INNER_FOLDER_DATABASES} -e DOCKER_MODULE_VARIANTANNOTATION_SUBMODULE_VARANK_FOLDER_DATA=${DOCKER_STARK_INNER_FOLDER_DATA} -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:rw -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_INNER_FOLDER_SERVICES}:rw -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG}:${DOCKER_STARK_INNER_FOLDER_CONFIG}:rw -v ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
            - MICROSERVICE_REPOSITORY=${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}
        volumes:
            # Main configuration
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_CONFIG}:ro
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_SERVICES}:${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_INNER_FOLDER_SERVICES}:rw
            
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_REPOSITORY}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_DEPOSITORY}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_DEPOSITORY}:rw
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVES}:${DOCKER_STARK_INNER_FOLDER_OUTPUT_ARCHIVES}:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:ro
            - ${DOCKER_STARK_SOCK_MOUNT}
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_HOST_FOLDER_CONFIG}/launcher.py:/app/bin/config/launcher.py:rw
            - ${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_CONTAINER_ENV_FILE}:/app/${DOCKER_STARK_MODULE_SUBMODULE_SERVICE_LISTENER_NAME}/STARK.env:rw

        networks: 
            - ${DOCKER_STARK_MAIN_NETWORK}

# NETWORK
###########

networks:
    
    stark_stark:
        external: true