{
  "submodules": {
    "varank": {
      "description": "Only VaRank annotation tool",
      "services": {
        "cli": {
          "code": "cli",
          "name": "VaRank cli",
          "type": "CLI",
          "description": "A VaRank CLI.",
          "release": "2.1",
          "available": true
        },
        "listener": {
          "code": "listener",
          "name": "VaRank listener",
          "type": "listener",
          "description": "A VaRank listener service is started as a daemon, listening for new STARK analyzed run (new folder in output/repository) and well configured (STARKComplete.txt without VaRankRunning.txt or VaRankComplete.txt), and check triggers to launch or not analysis.",
          "release": "1.1",
          "available": true
        } 
      }
    }
  }
}

